# Generated by Django 5.0.4 on 2024-06-27 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=30)),
                ("platform", models.CharField(max_length=30)),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("salary", models.IntegerField()),
                ("contract_length", models.CharField(max_length=15)),
                ("job_link", models.URLField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="job.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobStatusUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Rejected", "Rejected"),
                            ("Offered", "Offered"),
                            ("Accepted", "Accepted"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        default="Applied",
                        max_length=15,
                    ),
                ),
                (
                    "update_text",
                    models.CharField(default="Initialize Job", max_length=100),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="job.job",
                    ),
                ),
            ],
        ),
    ]
