# Generated by Django 5.0.4 on 2024-05-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_alter_job_applicant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="founded",
        ),
        migrations.RemoveField(
            model_name="company",
            name="size",
        ),
        migrations.RemoveField(
            model_name="company",
            name="website",
        ),
    ]
