# Generated by Django 5.0.4 on 2024-06-25 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_remove_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcomment",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobcomment",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="job.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobstatusupdate",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobstatusupdate",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="job.job",
            ),
        ),
    ]
